name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Debug versions
        run: |
          node --version
          npm --version
          grep -A12 '"node_modules/@esbuild/aix-ppc64"' package-lock.json || true
          grep -n '"@esbuild/aix-ppc64"' package-lock.json || true
          grep -n '"esbuild":' package-lock.json || true

      - name: Install dependencies 
        run: npm ci 

      - name: Run test
        run: npm run test
